name: Build and Deploy using publish profile
on:
  push
    
env:
  AZURE_WEBAPP_NAME: nodesample   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
     
    environment: dev
    steps:
    - name: Install Node
      uses: actions/setup-node@v1
      with: 
           node-version: '12.x'

    - name: Install newman
      run: |
        npm install -g newman

    - name: Run POSTMAN collection
      run: |
        newman run ./test/HttpbinForNewman.json -r cli

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
       
        node-version: ${{ env.NODE_VERSION }}
    - name: 'npm install, build, and test'
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        npm run compile
        npm install wil-api-test --save-dev
      
      
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
         
    
